name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_NAME: BigBang1112.Gbx/Server

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        submodules: recursive
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    
    - name: Add GitHub NuGet source
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bigbang1112-cz/index.json"
      
    - name: Build & Publish
      run: dotnet publish Src/${{env.PROJECT_NAME}} -c Release -o publish -p:PublishTrimmed=true --self-contained

    - name: Deploy to Ubuntu using Rsync
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr
        path: publish/ # trailing slash means copy content
        remote_path: /var/www/${{env.PROJECT_NAME}}
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.KEY }}
        
    - name: Restart the application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: sudo systemctl restart BigBang1112.Gbx
