name: Docker Image push to registry

on:
  push:
    branches: [ "main" ]
    
env:
  BUILD_DIR: Src/BigBang1112.Gbx/Server
  IMAGE_NAME: gbx-bigbang1112-cz
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       submodules: recursive
    - name: Add GitHub NuGet source
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bigbang1112-cz/index.json"
    - name: Build Docker image
      run: docker build . -f $BUILD_DIR/Dockerfile -t $REGISTRY_URL/$IMAGE_NAME
    - name: Push Docker image to registry
      run: |
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login $REGISTRY_URL --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin
        docker push $REGISTRY_URL/$IMAGE_NAME
